---
-
  hosts: lamp

  vars:
    mysql_root_password: password
    db_user: laravel
    db_pass: password
    db_name: laravel
  tasks:
    - name: updating cache
      apt:
        update_cache: true
        state: present

    - name: installing apache
      package:
        name: apache2
        state: present

    - name: installing php
      package:
        name:
          - python3-apt
          - python3-pip
          - php
          - php-cli
          - php-mysql
          - php-mbstring
          - php-zip
          - php-gd
          - php-curl
          - php-xml
          - php-bcmath
          - php-common
        state: present

    - name: install zip and other  app
      package:
        name:
          - zip
          - git
          - unzip
          - libapache2-mod-php
        state: present

    - name: install mysql
      package:
        name:
          - mysql-server
          - python3-pymysql
        state: present


    - name: apache restart
      service:
        name: apache2
        enabled: true
        state: restarted
      notify: Reloaded apache2

    - name: mysql enabled
      service:
        name: mysql
        enabled: true
        state: restarted


    - name: mysql manually start
      command: service mysql start

    - name: set mysql pass
      file:
        path: /tmp/script.sh
        state: touch
        mode: +x

    - name: echo data in script
      blockinfile:
        path: /tmp/script.sh
        block: |
          #!/bin/bash
          sudo mysql -u root << EOF
            ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY 'password';
          EOF
        state: present


    - name: run script file
      command: sh /tmp/script.sh

    - name: remove script from remote server
      file:
        name: /tmp/script.sh
        state: absent

    - name: enable rewrite module
      command: "a2enmod rewrite"
      notify: Reloaded apache2

    - name: creating mysql user)
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: creating medium_db
      mysql_db:
        login_user: "{{ db_user }}"
        login_password: "{{ db_pass }}"
        name: "{{ db_name }}"
        state: present

  handlers:
    - name: Reloaded apache2
      service:
        name: apache2
        state: reloaded

    - name: Restart mysql
      service:
        name: mysql
        state: restarted
